// ─── DONNÉES DES PROJETS ──────────────────────────────────────────────────────

export const FEATURED = [
  {
    id: 1, title: "Canal+U", category: "Design d'Innovation", year: "2023",
    image: "/projets/canalu/cover.jpg",
    images: [
      "/projets/canalu/cover.jpg",
      "/projets/canalu/team.jpg",
      "/projets/canalu/display.jpg",
      "/projets/canalu/media.jpg",
    ],
    tags: [
      { label: "3D", cat: "domain" },
      { label: "Unreal Engine 5", cat: "tool" },
      { label: "Blender", cat: "tool" },
      { label: "Direction artistique", cat: "domain" },
      { label: "Gestion de projet", cat: "domain" },
    ],
    accent: "#FBBEB4",
    desc: "Plateforme de Streaming innovanter, immersif, participatic & interactif pour Canal+",
    role: "Lead Designer", team: "20 personnes", duration: "2 semaines",
    contexte: "Canal+ cherchait à créer une expérience live immersive pour l'événement de lancement de leur offre jeunesse. Le défi était de concevoir un dispositif 3D interactif utilisable en temps réel par le public.",
    contribution: "J'ai assuré la direction artistique complète du projet et piloté une équipe de 20 personnes. J'ai défini le style visuel sous Unreal Engine 5, supervisé la modélisation 3D avec Blender, et géré le planning sur 2 semaines de production intensive.",
    resultats: "Livraison dans les délais malgré la contrainte de 2 semaines. L'expérience a accueilli plus de 500 visiteurs lors de l'événement. Retours très positifs de Canal+ qui a reconduit la collaboration.",
    lien: "https://www.behance.net/gallery/178570041/CanalU",
  },
  {
    id: 2, title: "Disney", category: "Design Print & Web", year: "2023",
    image: "/projets/disney/cover.jpg",
    images: [
      "/projets/disney/cover.jpg",
      "/projets/disney/bingo_disney_hotel_01.jpg",
      "/projets/disney/bingo_disney_hotel_02.jpg",
      "/projets/disney/disney_activity_book.jpg",
    ],
    tags: [
      { label: "Design Print", cat: "domain" },
      { label: "Figma", cat: "tool" },
      { label: "Photoshop", cat: "tool" },
      { label: "InDesign", cat: "tool" },
      { label: "Design Web", cat: "domain" },
      { label: "Gestion de projet", cat: "domain" },
    ],
    accent: "#D4A574",
    desc: "Supports print & digitaux pour Disney Hotels : jeu de bingo, livret d'activités et assets web. Project Lead sur 8 mois avec une équipe de 12.",
    role: "Project Lead", team: "12 personnes", duration: "8 mois",
    contexte: "Disney Hotels cherchait à enrichir l'expérience de ses clients en proposant des supports créatifs à l'effigie de ses personnages emblématiques. L'objectif : concevoir une gamme de supports print et digitaux — jeu de bingo, livret d'activités, assets web — en strict respect de la charte graphique Disney, tout en apportant une fraîcheur visuelle adaptée à un public familial. Le défi principal résidait dans les contraintes de validation propres à Disney : cycles longs, exigences élevées sur l'usage des personnages et des couleurs de marque, et nécessité de livrer des fichiers prêts à l'impression pour plusieurs formats.",
    contribution: "En tant que Project Lead, j'ai piloté une équipe de 12 personnes répartis entre design print, design web et production. J'ai défini le planning, réparti les briefs et supervisé chaque livrable de la conception à la mise en production. Sur le plan créatif, j'ai travaillé sous Figma pour les maquettes interactives et les assets web, Photoshop pour les retouches et les montages personnages, et InDesign pour la mise en page finale des supports imprimés. J'ai également assuré l'interface avec les équipes Disney lors des revues de validation, en traduisant leurs retours en actions concrètes pour l'équipe.",
    resultats: "L'intégralité des supports a été livrée dans les délais impartis et validée par Disney après plusieurs rounds de révisions. Le jeu de bingo et le livret d'activités ont été distribués dans les hôtels Disney, contribuant directement à l'expérience client sur site. Ce projet a renforcé notre positionnement comme prestataire capable de tenir les exigences d'un client grand compte à forte contrainte de marque, et a ouvert la voie à de nouvelles collaborations dans le secteur de l'entertainment.",
  },
  {
    id: 3, title: "Digital Event", category: "Application mobile", year: "2023",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=85",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=85",
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=85",
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&q=85",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=85",
    ],
    tags: [
      { label: "UI/UX", cat: "domain" },
      { label: "Motion design", cat: "domain" },
      { label: "Figma", cat: "tool" },
      { label: "After Effects", cat: "tool" },
    ],
    accent: "#FBBEB4",
    desc: "App de méditation immersive avec sound design custom. Coordination de 5 personnes.",
    role: "Product Designer", team: "5 personnes", duration: "4 mois",
    contexte: "[Décris ici le contexte du projet Disney : brief, enjeux, public cible, contraintes…]",
    contribution: "[Décris ici ta contribution : design des écrans, animations, coordination de l'équipe de 5…]",
    resultats: "[Décris ici les résultats : retours utilisateurs, métriques d'engagement, retour client…]",
  },
  {
    id: 4, title: "Color & Type Lab", category: "Outil interactif", year: "2024",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85",
      "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1200&q=85",
    ],
    tags: [
      { label: "UI/UX", cat: "domain" },
      { label: "Design system", cat: "domain" },
      { label: "React", cat: "tool" },
      { label: "Figma", cat: "tool" },
    ],
    accent: "#D4A574",
    desc: "Un outil interactif pour tester et analyser des combinaisons de couleurs et de typographies. Essaie la tienne !",
    role: "Designer & Développeur", team: "Solo", duration: "En continu",
    contexte: "[Décris ici le contexte de ce projet de direction artistique : commanditaire, objectif, contraintes créatives…]",
    contribution: "[Décris ici ton travail : concept, illustrations, choix typographiques, production…]",
    resultats: "[Décris ici les résultats : diffusion, retours, récompenses éventuelles…]",
  },
];

export const CAROUSEL = [
  {
    id: 11, title: "Unreal Engine 5 · 3D", category: "3D & Motion Design", year: "2023",
    image: "https://img.youtube.com/vi/pJ_CZmqbvvg/maxresdefault.jpg",
    tags: [{ label: "3D", cat: "domain" }, { label: "Unreal Engine 5", cat: "tool" }, { label: "Blender", cat: "tool" }],
    accent: "#FBBEB4",
    page: "unreal",
  },
  { id: 5, title: "Liminal", category: "Recherche UX", year: "2025", image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80", tags: [{ label: "UX Research", cat: "domain" }, { label: "Stratégie", cat: "domain" }], accent: "#FBBEB4" },
  { id: 6, title: "Kintsugi", category: "Webdesign", year: "2024", image: "https://images.unsplash.com/photo-1493397212122-2b85dda8106b?w=600&q=80", tags: [{ label: "Webdesign", cat: "domain" }, { label: "Webflow", cat: "tool" }], accent: "#D4A574" },
  { id: 7, title: "Lumen", category: "Design system", year: "2026", image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80", tags: [{ label: "Design system", cat: "domain" }, { label: "Figma", cat: "tool" }], accent: "#FBBEB4" },
  { id: 8, title: "Sansei", category: "Édition", year: "2026", image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80", tags: [{ label: "Édition", cat: "domain" }, { label: "InDesign", cat: "tool" }], accent: "#D4A574" },
  { id: 9, title: "Mirage", category: "Portfolio", year: "2025", image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&q=80", tags: [{ label: "Webdesign", cat: "domain" }, { label: "React", cat: "tool" }], accent: "#FBBEB4" },
  { id: 10, title: "Helix", category: "Branding", year: "2024", image: "https://images.unsplash.com/photo-1634942537034-2531766767d1?w=600&q=80", tags: [{ label: "Branding", cat: "domain" }, { label: "Illustrator", cat: "tool" }], accent: "#D4A574" },
];
